#!/bin/bash
echo 'root:password' | sudo chpasswd;
sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - ;
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' ;
sudo apt-get update ;
sudo apt-get -y install lxde ubuntu-gnome-desktop tightvncserver xrdp flashplugin-installer chromium-browser firefox google-chrome-stable;
sudo echo lxsession -s LXDE -e LXDE > ~/.xsession; 
sudo echo "CHROMIUM_FLAGS=\" --user-data-dir --no-sandbox\"" > sudo /etc/chromium-browser/default; 
sudo echo "chromium-browser --no-sandbox http://google.com&" >> ~/a;  
sudo echo "google-chrome --no-sandbox http://google.com&" >> ~/c  ;
sudo echo "firefox --no-sandbox http://google.com&" >> ~/d;   
chmod +x ~/a ~/c ~/d;
sudo cp ~/a /root;
sudo cp ~/c /root;
sudo cp ~/d /root;
sudo touch /etc/xdg/autostart/google-chrome-autostart.desktop /etc/xdg/autostart/terminal-autostart.desktop ;
sudo chmod 777 /etc/xdg/autostart/google-chrome-autostart.desktop /etc/xdg/autostart/terminal-autostart.desktop /etc/xdg/autostart/restore-lxde-session-autostart.desktop;
sudo echo -e "[Desktop Entry]\nType=Application\nName=Google Chrome\nGenericName=Google chrome autostart configuration\nComment=This will open google chrome when gnome starts up\nExec=sudo sensible-browser --no-sandbox --restore-last-session\nTerminal=true\nType=Application\nX-GNOME-Autostart-enabled=true" | cat > /etc/xdg/autostart/google-chrome-autostart.desktop;
sudo echo -e "[Desktop Entry]\nType=Application\nName=Terminal\nGenericName=Terminal autostart configuration\nComment=This will open default terminal program when gnome starts up\nExec=x-terminal-emulator\nTerminal=true\nType=Application\nX-GNOME-Autostart-enabled=true" | cat > /etc/xdg/autostart/terminal-autostart.desktop;
sudo chmod 777 /etc/xrdp/xrdp.ini;
sudo echo -e "[globals]\nbitmap_cache=yes\nbitmap_compression=yes\nport=3389\ncrypt_level=low\nchannel_code=1\nmax_bpp=24\n\n[xrdp1]\n\nname=Jishnu Customized\nlib=libvnc.so\nusername=ask\npassword=ask\nip=127.0.0.1\nport=ask-1" | cat > /etc/xrdp/xrdp.ini;
echo sudo /etc/init.d/xrdp restart;
